### ISSUE TITLE
Address channels’ lack of thread-safety

### ISSUE THREAD

**Issue by MerelyAPseudonym** [clojurewerkz/langohr.docs#20]
The official RabbitMQ documentation states that: <q cite="https://web.archive.org/web/20150910122702/http://www.rabbitmq.com/api-guide.html#channel-threads"><code>Channel</code> instances must not be shared between threads. Applications should prefer using a <code>Channel</code> per thread instead of sharing the same <code>Channel</code> across multiple threads.</q>

I don’t yet have an opinion on whether the documentation should merely warn developers, or whether the code snippets should be modified.

**Comment by MerelyAPseudonym** [comment]
Note that [the Message Acknowledgements example](https://github.com/clojurewerkz/langohr.docs/blob/c1e073f3c2aa8c81522de9f51a8228db38782366/articles/queues.md#message-acknowledgements) *does* demonstrate opening multiple channels for multiple consumers, but it also creates multiple connections which (IIUC) is unnecessary.

**Comment by michaelklishin** [comment]
Only concurrent publishing is not supported. Concurrent consumers should pose no problem. The root of the issue is in on the wire framing of `basic.publish` frame sets. `basic.consume` is a single frame, so incorrect interleaving on a channel is not possible.

**Comment by michaelklishin** [comment]
It doesn't really matter whether some examples use more connections than technically necessary. They are **examples**, not code snippets that should be blindly copied without understanding. Using separate connections is a reasonable way of representing multiple connected clients, which is the case in any practical messaging-based system.

**Comment by MerelyAPseudonym** [comment]
@michaelklishin oh, good to know! Thanks.

For :star2: **bonus OSS maintainer points** :star2: would you be able to recommend a resource for learning more about the wire framing? Or is there nothing better than [the official AMQP 0-9-1 spec](https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf)?

**Comment by michaelklishin** [comment]
I only used the spec. Wireshark 2.0 rc can be very helpful and now has a section on rabbitmq.com.



MK
